<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>141997e7-0a5d-46ce-b1d4-b522cf1e8dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.header-action-text.black--text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-action-text ') and contains(concat(' ', normalize-space(@class), ' '), ' black--text ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68807268-15f6-4d4c-84c4-dd0f0f7acb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-action-text black--text px-0</value>
      <webElementGuid>192390c9-a0a0-4e2f-9bef-54c75ccf2a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Login
                  </value>
      <webElementGuid>4cf1d1b5-a32d-4f88-8e83-7033afd3d678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b8c3dcf8f4ae95ab64a18c0c2fb93b71</value>
      <webElementGuid>642c2c68-6a35-4c8e-a323-0950e4e4e617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-action-text ') and contains(concat(' ', normalize-space(@class), ' '), ' black--text ')]</value>
      <webElementGuid>60a96d2b-4e84-4b95-ad6a-0e42ff9e1244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-action-text ') and contains(concat(' ', normalize-space(@class), ' '), ' black--text ')]</value>
      <webElementGuid>e9ebc276-face-4d25-ba75-3275f277753e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                    Login
                  ' or . = '
                    Login
                  ')]</value>
      <webElementGuid>8222a463-a125-4820-81a3-ed3fa8d51fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
