<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>2bf8d0e1-68cf-4880-b6e6-096aa5d67ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.v-btn--rounded.primary .v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn--rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' primary ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn__content ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff396e74-0baf-45c9-a2dc-b7a5ea6eacff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>3e43249d-c960-4149-9bea-591479061e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Continue
  </value>
      <webElementGuid>5eeb5850-3a2c-4232-a3d5-f0f0707c8cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1d1809bda2ac4c35df8ac878e38c27d8</value>
      <webElementGuid>c24c1f03-fe47-4d12-a73a-91932631e54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn--rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' primary ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn__content ')]</value>
      <webElementGuid>daf04857-dc30-4794-a37f-fa1ca56c6098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn--rounded ') and contains(concat(' ', normalize-space(@class), ' '), ' primary ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-btn__content ')]</value>
      <webElementGuid>dcb3b51b-5b63-4006-8df3-561d40fd5220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
    Continue
  ' or . = '
    Continue
  ')]</value>
      <webElementGuid>c279cf93-4d21-48e9-b6a8-47164a4737f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
